// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CryptoController from "./crypto_controller"
application.register("crypto", CryptoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedCommentsController from "./nested_comments_controller"
application.register("nested-comments", NestedCommentsController)

import TrackedController from "./tracked_controller"
application.register("tracked", TrackedController)
